### ISSUE TITLE
js code

### ISSUE THREAD

**Issue by mtsio** [ioa-maellak/weather-station#3]
Ο κώδικας που προστέθηκε σε javascript καλό είναι να μπει σε διαφορετικό branch ή σε κάποιον άλλον φάκελο ή σε διαφορετικό repository. Βάζω εδώ το issue γιατί οι @ebrachos και @katekats δε φαίνεται να είναι στο forge ως members του project. 
Επίσης δε βλέπω το λόγο να βάζουμε τα issues στο forge και όχι στο github, αλλά μάλλον πρέπει να δημιουργηθεί διαφορετικό issue γι' αυτό.

**Comment by karabill** [comment]
Ekana sto forge.
Genika proteino na xrhhsmopoioyme to forge giati einai fitagmeno apo to ellak (an kai pio dysxristo). An exete megalo problhma, xrhshmopoioyme ayto edo.

Gia to kodika, an thes ftiakse ena fakelo esy kai metefereta mesa, allios tha to kano ego ayrio.

**Comment by mtsio** [comment]
Απλά διευκολύνει κάποια πράγματα να έχουμε τα issues εδώ (π.χ να μπορείς
πολύ εύκολα να τα αναφέρεις στα commit ή σε άλλα issues αν βάλεις #
μπροστά από τον αριθμό)

Vasileios Karavasilis:

**Comment by karabill** [comment]
Eftiaksa enan alla fakelo playground. Ekei mesa bazoyme oti theloyme.

Me to issue tha to shzhthso ligo kai me toys ypoloipoys, alla mporoyme na xrhshmopoioyme to git gia olh thn xrhsh. Sto forge na bazoyme ena link mono oti ypirke ayto to problhma.
